name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LOG_LEVEL: debug

jobs:
  validate-renovate-config:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        file:
          - default.json
          - renovate-config.json
    env:
      RENOVATE_CONFIG_FILE: ${{ matrix.file }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Validate Renovate Config
        run: npx -p renovate@latest renovate-config-validator
